# Generated by Django 4.0.6 on 2022-08-17 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientids',
            unique_together={('client', 'type', 'country')},
        ),
    ]
