# Generated by Django 4.0.6 on 2022-08-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('clients', '0002_alter_clientids_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddresses',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='master.country'),
        ),
    ]
