# Generated by Django 4.0.6 on 2022-08-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clientaddresses_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddresses',
            name='city',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientaddresses',
            name='type',
            field=models.CharField(choices=[('HOME', 'Home'), ('BUSINESS', 'Business'), ('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('CONTRACT', 'Contract'), ('RECIPIENT', 'Recipient')], max_length=16),
        ),
    ]
