# Generated by Django 4.0.6 on 2022-08-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprice',
            name='last_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
