# Generated by Django 4.0.6 on 2022-08-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccountledger',
            name='amount',
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='balance',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=48),
        ),
        migrations.AddField(
            model_name='clientaccountledger',
            name='balance',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=48),
        ),
    ]
