# Generated by Django 4.0.6 on 2022-07-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('iso_code', models.CharField(max_length=3)),
                ('code', models.CharField(default='$', max_length=3)),
            ],
        ),
    ]
