# Generated by Django 4.0.6 on 2022-08-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
