# Generated by Django 4.0.6 on 2022-08-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproduct',
            name='can_collector',
            field=models.BooleanField(default=True),
        ),
    ]
