# Generated by Django 4.0.6 on 2022-08-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_accountproduct_can_collector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountproduct',
            name='can_collector',
        ),
        migrations.AddField(
            model_name='accountproduct',
            name='collector',
            field=models.BooleanField(default=False),
        ),
    ]
