# Generated by Django 4.0.6 on 2022-07-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_loanproduct_nominal_interes_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='repayment_step',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
