# Generated by Django 4.0.6 on 2022-08-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_remove_accountproduct_can_collector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='days_in_years',
            field=models.CharField(choices=[('360', ' 360'), ('364', ' 364'), ('365', ' 365')], max_length=8),
        ),
    ]
