# Generated by Django 4.0.6 on 2022-07-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
