# Generated by Django 4.0.6 on 2022-08-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='last_user',
            new_name='subimtted_by',
        ),
    ]
