# Generated by Django 4.0.6 on 2022-07-16 20:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_remove_clientaccount_id_clientaccount_uuid'),
        ('loans', '0002_delete_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPurpose',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('principal', models.DecimalField(decimal_places=16, max_digits=48)),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_on', models.DateTimeField()),
                ('disbursement_on', models.DateTimeField()),
                ('number_of_repayments', models.SmallIntegerField()),
                ('first_repayment_on', models.DateTimeField()),
                ('nominal_interes_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
                ('loan_prupose', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loanpurpose')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
