# Generated by Django 4.0.6 on 2022-08-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanledger',
            name='paid_out',
            field=models.BooleanField(default=False),
        ),
    ]
