# Generated by Django 4.0.6 on 2022-08-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loanledger_paid_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanledger',
            old_name='balance',
            new_name='payment_amount',
        ),
    ]
