# Generated by Django 4.0.6 on 2022-07-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='nominal_interes_rate',
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursement_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='first_repayment_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='submitted_on',
            field=models.DateField(),
        ),
    ]
