# Generated by Django 4.0.6 on 2022-08-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_rename_balance_loanledger_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanledger',
            name='payment_amount',
        ),
    ]
