# Generated by Django 4.0.6 on 2022-08-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_remove_loanledger_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanledger',
            name='payment_amount',
            field=models.DecimalField(decimal_places=16, default=0.0, max_digits=48),
        ),
    ]
