# Generated by Django 4.0.6 on 2022-08-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loanledger_payment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='balance',
            new_name='principal',
        ),
    ]
